<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>{{ $title ?? 'Report' }}</title>
    <style>
        body {
            font-family: 'Helvetica Neue', 'Helvetica', Arial, sans-serif;
            font-size: 10px;
            color: #111;
            line-height: 1.4;
            margin: 0;
            padding: 0;
        }
        
        /* Typography */
        .company-name { font-size: 18px; font-weight: bold; margin-bottom: 2px; }
        .report-title { font-size: 16px; margin-bottom: 5px; text-transform: uppercase; letter-spacing: 1px; }
        .section-title { font-size: 12px; font-weight: bold; margin-top: 15px; margin-bottom: 10px; border-bottom: 1px solid #333; padding-bottom: 3px; }
        .text-right { text-align: right; }
        .text-center { text-align: center; }
        .font-bold { font-weight: bold; }
        
        /* Header */
        .header-table { width: 100%; margin-bottom: 30px; border-bottom: 2px solid #333; padding-bottom: 15px; }
        .header-meta td { font-size: 9px; color: #555; line-height: 1.5; }
        
        /* Executive Summary Cards */
        .summary-wrapper { width: 100%; margin-bottom: 25px; }
        .summary-card { border: 1px solid #ddd; padding: 6px 10px; text-align: left; background-color: #fafafa; }
        .summary-card-title { font-size: 9px; color: #666; margin-bottom: 3px; text-transform: uppercase; font-weight: bold;}
        .summary-card-value { font-size: 14px; font-weight: bold; }
        .text-asset { color: #10b981; } /* Emerald */
        .text-liability { color: #f59e0b; } /* Amber */
        .text-equity { color: #3b82f6; } /* Blue */
        
        /* Tables */
        table.data-table { width: 100%; border-collapse: collapse; margin-bottom: 15px; }
        table.data-table th { background-color: #fff; border-bottom: 1px solid #333; padding: 6px; font-size: 10px; font-weight: bold; text-align: left; }
        table.data-table th.text-right { text-align: right; }
        table.data-table td { padding: 5px 6px; font-size: 10px; }
        table.data-table tr:nth-child(even) td { background-color: #fdfdfd; }
        
        /* Totals */
        .total-row td { font-weight: bold; border-top: 1px solid #333 !important; border-bottom: 3px double #333 !important; font-size: 11px; padding-top: 8px; padding-bottom: 8px; background-color: #fff !important; }
        .subtotal-row td { font-weight: bold; border-top: 1px solid #999 !important; padding-top: 6px; padding-bottom: 6px; background-color: #fff !important; }
        
        /* Layout Utilities */
        .w-100 { width: 100%; }
        .w-50 { width: 50%; }
        .align-top { vertical-align: top; }
        .clear { clear: both; }
        .mb-20 { margin-bottom: 20px; }
        
        /* Footer */
        footer { position: fixed; bottom: -30px; left: 0px; right: 0px; height: 30px; border-top: 1px solid #ddd; padding-top: 5px; font-size: 8px; color: #777; }
        .footer-table { width: 100%; }
        .pagenum:before { content: counter(page); }
    </style>
</head>
<body>
    <footer>
        <table class="footer-table" cellpadding="0" cellspacing="0">
            <tr>
                <td width="33%">Generated by Ledger-Pro v3.1</td>
                <td width="33%" class="text-center">Confidential Financial Report</td>
                <td width="33%" class="text-right">Page <span class="pagenum"></span> of <span class="pagenum"></span></td>
            </tr>
        </table>
    </footer>

    <table class="header-table" cellpadding="0" cellspacing="0">
        <tr>
            <td width="60%" class="align-top">
                @if(isset($logoPath) && $logoPath)
                    <img src="{{ $logoPath }}" style="max-height: 40px; margin-bottom: 10px;" alt="Logo">
                @endif
                <div class="company-name">{{ $companyName }}</div>
                <div class="report-title">{{ $title }}</div>
                <div class="font-bold">{{ $period }}</div>
            </td>
            <td width="40%" class="align-top text-right header-meta">
                <table width="100%" cellpadding="0" cellspacing="0">
                    <tr><td class="text-right font-bold" width="60%">Prepared By:</td><td class="text-right" width="40%">Ledger-Pro</td></tr>
                    <tr><td class="text-right font-bold">Generated On:</td><td class="text-right">{{ $generatedAt }}</td></tr>
                    <tr><td class="text-right font-bold">Currency:</td><td class="text-right">{{ $currency ?? '' }}</td></tr>
                    @if(isset($reportId))
                    <tr><td class="text-right font-bold">Report ID:</td><td class="text-right">{{ $reportId }}</td></tr>
                    @endif
                </table>
            </td>
        </tr>
    </table>

    <div class="content">
        @yield('content')
    </div>
</body>
</html>
